### ISSUE TITLE
This method could be in a controller utility file, since it could be used by N controllers

### ISSUE THREAD

**Issue by luisroxx** [barbarafv/golang-rest-api#3]
You could create something like., utils inside controller folder and put this method there so any controller we could have in the future could use it. instead of duplicating code
https://github.com/barbarafv/golang-rest-api/blob/838e82832737f2c88c923d18e321605e72db98c2/source/controllers/planets/planet.go#L50-L56

**Comment by barbarafv** [comment]
done
