### ISSUE TITLE
Stop putting pointers in slice

### ISSUE THREAD

**Issue by luisroxx** [barbarafv/golang-rest-api#33]
Why?, because you dont need it

https://medium.com/swlh/golang-tips-why-pointers-to-slices-are-useful-and-how-ignoring-them-can-lead-to-tricky-bugs-cac90f72e77b#:~:text=The%20pointer%20to%20a%20slice,those%20who%20call%20the%20function.

https://github.com/barbarafv/golang-rest-api/blob/3fe66da413abefe4f839738c7bfb34d2c0d7bfba/source/service/planet.go#L36-L49

**Comment by barbarafv** [comment]
done
